global:
  client: xfreerdp
  connection_string: sqlite:///myrdp.sqlite
  # logging level: debug, info, warning, error, critical
  log_level: info

xfreerdp:
  executable: xfreerdp
  args: "+clipboard /cert-ignore +drives -themes +compression /gdi:sw +auto-reconnect -sec-nla"

rdesktop:
  executable: rdesktop
  args: "-z -r disk:test=/home -x m"
